#!/bin/bash

as -o out/main.o main.s && 
as -o out/stepOutlet.o stepOutlet.s && 
as -o out/stepColorWheel.o stepColorWheel.s && 
as -o out/startFeeder.o startFeeder.s && 
as -o out/stopFeeder.o stopFeeder.s &&
as -o out/setMotorPins.o setMotorPins.s &&
as -o out/clearMotorPins.o clearMotorPins.s && 
gcc -o out/main out/main.o out/stepOutlet.o out/stepColorWheel.o out/startFeeder.o out/stopFeeder.o out/setMotorPins.o out/clearMotorPins.o &&
./out/main #gdb --args 