#!/bin/bash

as -o out/mainTest1.o mainTest1.s && 
as -o out/stepOutlet.o stepOutlet.s && 
as -o out/stepColorWheel.o stepColorWheel.s && 
as -o out/startFeeder.o startFeeder.s && 
as -o out/stopFeeder.o stopFeeder.s &&
as -o out/setMotorPins.o setMotorPins.s &&
as -o out/clearMotorPins.o clearMotorPins.s && 
as -o out/moveOutletToNextPosition.o moveOutletToNextPosition.s &&
as -o out/sortTest1.o sortTest1.s &&
gcc -o out/mainTest1 out/mainTest1.o out/stepOutlet.o out/stepColorWheel.o out/startFeeder.o out/stopFeeder.o out/setMotorPins.o out/clearMotorPins.o out/moveOutletToNextPosition.o out/sortTest1.o &&
./out/mainTest1 #gdb --args 