#!/bin/bash

as -o out/main.o main.s && 
as -o out/sort.o sort.s && 
as -o out/readPin.o readPin.s && 
as -o out/stepOutlet.o stepOutlet.s && 
as -o out/stepColorWheel.o stepColorWheel.s && 
as -o out/startFeeder.o startFeeder.s && 
as -o out/stopFeeder.o stopFeeder.s &&
as -o out/setMotorPins.o setMotorPins.s &&
as -o out/clearMotorPins.o clearMotorPins.s && 
as -o out/colorDetection.o colorDetection.s && 
as -o out/moveOutletToNextColor.o moveOutletToNextColor.s && 
as -o out/calibrateOutlet.o calibrateOutlet.s && 
as -o out/calibrateColorWheel.o calibrateColorWheel.s && 
as -o out/checkCounter.o checkCounter.s && 
as -o out/waitForStartButton.o waitForStartButton.s && 
gcc -o out/main out/main.o out/stepOutlet.o out/stepColorWheel.o out/startFeeder.o out/stopFeeder.o out/setMotorPins.o out/clearMotorPins.o out/colorDetection.o out/moveOutletToNextColor.o out/sort.o out/calibrateColorWheel.o out/calibrateOutlet.o out/readPin.o out/checkCounter.o out/waitForStartButton.o &&
./out/main #gdb --args 