#!/bin/bash

as -o out/main.o main.s && 
as -o out/stepColorWheel.o stepColorWheel.s && 
as -o out/calibrateColorWheel.o calibrateColorWheel.s && 
as -o out/readPin.o readPin.s && 
gcc -o out/main out/main.o out/stepColorWheel.o out/calibrateColorWheel.o out/readPin.o &&
gdb --args ./out/main