#!/bin/bash

as -o out/main.o main.s && 
as -o out/moveOutletToNextColor.o moveOutletToNextColor.s && 
as -o out/stepOutlet.o stepOutlet.s && 
# gcc -o out/main out/main.o out/moveOutletToNextColor.o out/mmCounterIncrementAndPrintMessageFunctions.o out/stepOutlet.o &&
gcc -o out/main out/moveOutletToNextColor.o out/stepOutlet.o
./out/main #gdb --argsls
